LVSA.Newsletter.Presentation/ViewModels/EnviaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LVSA.Newsletter.Presentation.ViewModels
{
    public class EnviaViewModel : IValidatableObject
    {
        public string Tipo { get; set; }
        [Required]
        public Guid ServidorId { get; set; }
        [Required]
        public Guid RemetenteId { get; set; }
        public string Assunto { get; set; }
        public string Body { get; set; }
        public string SMS { get; set; }
        [Required]
        public HttpPostedFileBase Arquivo { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Tipo == "Text/SMS")
            {
                if (string.IsNullOrWhiteSpace(SMS))
                    yield return new ValidationResult("O campo é obrigatório.", new[] { "SMS" });

            }
            else if (Tipo == "Mail")
            {
                if (string.IsNullOrWhiteSpace(Assunto))
                    yield return new ValidationResult("O campo é obrigatório.", new[] { "Assunto" });
                if (string.IsNullOrWhiteSpace(Body))
                    yield return new ValidationResult("O campo é obrigatório.", new[] { "Body" });
            }
        }
    }
}

LVSA.Newsletter.Presentation/Controllers/EnviaController.cs
using LVSA.Newsletter.Application.Interfaces;
using LVSA.Newsletter.Application.ViewModels;
using LVSA.Newsletter.Presentation.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace LVSA.Newsletter.Presentation.Controllers
{
    public class EnviaController : Controller
    {
        private readonly IServidorAppService _servidorAppService;
        private readonly IRemetenteAppService _remetenteAppService;
        private readonly IEnvioAppService _envioAppService;

        public EnviaController(IServidorAppService servidorAppService, IRemetenteAppService remetenteAppService, IEnvioAppService envioAppService)
        {
            _servidorAppService = servidorAppService;
            _remetenteAppService = remetenteAppService;
            _envioAppService = envioAppService;
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);

            ViewBag.ServidorSet = _servidorAppService.Filtrar(f => true);
            ViewBag.RemetenteSet = _remetenteAppService.Filtrar(f => true);
        }

        // GET: Envia
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SMS(EnviaViewModel model)
        {
            ViewBag.Tipo = "Text/SMS";
            ViewBag.ServidorId = model.ServidorId;
            ViewBag.RemetenteId = model.RemetenteId;

            if (!ModelState.IsValid)
                return View("Index", model);

            string[] destinarios;
            MemoryStream m = new MemoryStream();

            string all;
            using (StreamReader sr = new StreamReader(model.Arquivo.InputStream))
                all = sr.ReadToEnd();

            destinarios = all.Replace("\r\n", "\n").Split('\n');

            DestinatarioViewModel[] destinatarioSet = destinarios.Select(s =>
            {
                string[] temp = s.Split(';');
                return new DestinatarioViewModel { Nome = temp[0], Email = temp[1], Celular = temp[2] };
            }).ToArray();

            _envioAppService.EnviarSMS(new LoteViewModel
            {
                RemetenteId = model.RemetenteId,
                Envio = new EnvioViewModel
                {
                    Body = model.SMS,
                    DestinatarioSet = destinatarioSet
                }
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Mail(EnviaViewModel model)
        {
            ViewBag.Tipo = "E-mail";
            ViewBag.ServidorId = model.ServidorId;
            ViewBag.RemetenteId = model.RemetenteId;

            return View("Index");
        }
    }
}

LVSA.Newsletter.Presentation/Views/Envia/Index.cshtml
@model LVSA.Newsletter.Presentation.ViewModels.EnviaViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Envia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Tipo de envio</label>
            <div class="col-md-10">
                <div>
                    <label>
                        <input type="radio" value="Text/SMS" @(ViewBag.Tipo == "Text/SMS" ? "checked" : "") name="Tipo" class="ace" />
                        <span class="lbl"> Text/SMS</span>
                    </label>
                </div>
                <div>
                    <label>
                        <input type="radio" value="E-mail" @(ViewBag.Tipo == "E-mail" ? "checked" : "") name="Tipo" class="ace" />
                        <span class="lbl"> E-mail</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Servidor</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ServidorId, new SelectList(ViewBag.ServidorSet, "Id", "Nome", "Funcao", Model?.ServidorId), "Selecione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServidorId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Remetente</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RemetenteId, new SelectList(ViewBag.RemetenteSet, "Id", "Nome", Model?.RemetenteId), "Selecione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RemetenteId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group sms" style="display:none;">
            <label class="control-label col-md-2">Text/SMS</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.SMS, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SMS, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group mail" style="display:none;">
            <label class="control-label col-md-2">Assunto</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Assunto, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Assunto, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group mail" style="display:none;">
            <label class="control-label col-md-2">Corpo e-mail</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Lista de destinatários</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Arquivo, new { @class = "", @type = "file" })
                @Html.ValidationMessageFor(model => model.Arquivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <button type="submit" formaction="@Url.Action("SMS")" class="btn btn-primary sms">Enviar Text/SMS</button>
        <button type="submit" formaction="@Url.Action("Mail")" class="btn btn-primary mail">Enviar E-mail</button>
    </div>


}


@section scripts {
    <script>
        $(function () {

            $('select[name="ServidorId"]')
                    .find('optgroup').hide();



            $('input[name="Tipo"]').change(function () {

                $('select[name="ServidorId"]').val('');

                $('select[name="ServidorId"]')
                    .find('optgroup[label="' + $(this).val() + '"]').show();

                $('select[name="ServidorId"]')
                    .find('optgroup:not([label="' + $(this).val() + '"])').hide();

                if ($(this).val() == "Text/SMS") {
                    $('.form-group.sms').show();
                    $('.form-group.mail').hide();
                }
                else if ($(this).val() == "E-mail") {
                    $('.form-group.mail').show();
                    $('.form-group.sms').hide();
                }
                else {
                    $('.form-group.mail').hide();
                    $('.form-group.sms').hide();
                }
            });

            $('input[name="Tipo"]:checked').trigger('change');

        });
    </script>
}